### ISSUE TITLE
Crowdin Translating saving problem

### ISSUE THREAD

**Issue by markssarGit** [neos/BuildEssentials#37]
I translated necessary texts into Crowdin in Latvian, but after a few days the servers show that these texts have not been translated. Why the server returns to backup mode in a few days? Is it another problem?

**Comment by kdambekalns** [comment]
I am currently evaluating Weblate as a replacement for CrowdIn, it looks really promising and should make this problem go away. Stay tuned!

**Comment by comradekingu** [comment]
@kdambekalns Great idea. Feel free to add https://hosted.weblate.org/user/kingu/ as an admin once set up.
Did you send in the form at https://hosted.weblate.org/hosting/ ? :)

**Comment by kdambekalns** [comment]
All on Weblate now (finally), updated instructions on the Neos website will follow.
