### ISSUE TITLE
Release notes use wrong URL to upgrade instructions

### ISSUE THREAD

**Issue by kdambekalns** [neos/BuildEssentials#58]
It shoud be

    https://docs.neos.io/cms/references/upgrade-instructions/upgrade-instructions-$versionSlug

instead of

    https://www.neos.io/download-and-extend/upgrade-instructions-$versionSlug.html

**Comment by albe** [comment]
Closing as of https://github.com/neos/BuildEssentials/commit/e67f478dff3c4e52d1295edd23e3c161cf286c7f (upmerge coming)
